# Generated by Django 4.0.4 on 2022-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Pnumber', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
