# Generated by Django 4.0.4 on 2022-05-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Pnumber',
            field=models.IntegerField(max_length=500, null=True),
        ),
    ]
