# Generated by Django 4.0.4 on 2022-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_feedback_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Pnumber',
            field=models.IntegerField(null=True),
        ),
    ]
